name: Hackage publish

on:
  push:
    branches: ["trunk"]

concurrency: 
  group: ${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6' 
          cabal-version: '3.0.0.0'
      - run: |
          cabal update
          cabal test
      - run: cabal sdist -o .
      - uses: haskell-actions/hackage-publish@v1
        with:
          hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
          packagesPath: .
          publish: true
